### PR TITLE
Show measured riding / running performance on the Fitness graph

### PR DESCRIPTION
**Pull request by OndrejSpanel**
This PR adds an option to show riding / running performance on the Fitness graph.

Running performance is computed as:

- grade adjusted pace * HRR

The running performance is your estimated fastest pace (estimated pace at your maximum heart rate).

Riding performance is computed as:

- weighted average power / HRR

The riding performance is your estimated maximum power (power at your maximum heart rate).

See following article for theorerical background: http://www.runnersworld.com/sweat-science/tracking-fitness-with-the-heart-rate-running-speed-index

Note: the same theory is used in the recent efforts graph extension (#278, already included as experimental).

Implementation notes:

- I did not find a way how to obtain Grade Adjusted Pace from current activities, therefore I am computing it on my own. This means cached data format is changed (new data added) and the cache must be invalidated when this update is installed
- so far I did not find a way how to get running pace units from the Helper, therefore I am always using minutes per kilometer.
- I wanted to use second y-axis on the right side of the graph, however I was unable to add it. The performance data scale is completely different from Fitness / Freshness data (and even riding scale is different from running). I am not much sure how important is this, though, as the data are most meaningful as relative anyway, showing trends.

Running performance is the violet dashed line, riding performance is the cyan one. Both are rendered as filtered and unfiltered, unfiltered are mush less visible (less opaque), filtered remove outliers (activities whose performance differs too much from neighbouring ones, in my cases these are mostly orienteering).

image

I guess some cleanup will be needed for this PR, and perhaps introducing another experimental option.  I did not want to spend time cleaning up before there is some feeback for this extension.

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@OndrejSpanel don't worry i will dive into your big pr soon ;) thx for this work !

**Comment by OndrejSpanel** [comment]
One more comment: while I did not find the performance graphs very reliable in my case (they do not seem to correlate much with a real racing / segment performance), knowing HR - GAP / Power relation opens a possibility of implementing an interesting feature: one can compute TRIMP quite even for biking / running activities with no HR data. The more often you wear HR sensor, the more reliable those data will be, but I think even providing a sensible estimation for workouts with no HR is better then just skipping them completely.

I hope to find time to try this sometimes soon.

**Comment by OndrejSpanel** [comment]
I have rebased the PR against the current head. Everything seems to be working fine, with one exception: somehow colors of my "measured power" in the Fitness graph do not obey my settings in `IColors` (actually no changes I make there seem to have any effect for me).

**Comment by OndrejSpanel** [comment]
Is anything else needed? I can rebase again against the current head, or adjust the code to any guidelines how can provide, if you wish.

**Comment by OndrejSpanel** [comment]
> don't worry i will dive into your big pr soon ;) thx for this work !

I have to admit I worry a bit now. The changes you did in Fitness Trend meanwhile are quite extensive and it will not be easy to merge this any more.

**Comment by thomaschampagne** [comment]
@OndrejSpanel You right. Merging your PR via Git to the new Angular 5 app is not possible. I postponed your PR merge to reduce the technical debt brought by AngularJS (v1)

Like i did for others features: I will migrate your feature/code inside angular 5 components and services with unit testing coverage. I don't know when by the way. i had to stabilize current one and produce postponed planned features by the same switch.

A new graph "view" seems to be required since your feature is another representation of fitness which not based on CTL/ATl/TSB model. Maybe i'm wrong?!

Tom

**Comment by OndrejSpanel** [comment]
> new graph "view"

I am not sure what "view" do you mean here. It makes sense to display this as a part of Fitness Trend as another curve, but the units on the y-axis are different (in fact each sport has different units - running and riding performance are not the same).

**Comment by thomaschampagne** [comment]
>It makes sense to display this as a part of Fitness Trend as another curve

Exactly ;) :)

**Comment by thomaschampagne** [comment]
@OndrejSpanel i'm closing that PR because of https://github.com/thomaschampagne/stravistix/issues/549

**Pull request closed without merging**
