### PR TITLE
Actually deal with other number formats when parsing goals

### PR DESCRIPTION
**Pull request by Holiverh**
Follow up for #302 and this time I swear it's for realsies. 😊

Turns out Strava actually has loads of (well, at least three) different number formats. As @Langlaeufer astutely pointed out in #302, I should just strip all non-numeric characters, instead of trying to be smart. My bad. Also I got rid of the whole trying to deal with decimals. I don't think Strava actually includes them anyway -- although I wish I could be more confident in that assertion.

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Thanks man ! Good work 👍 

Merging this and release this week ;)

Tom

**Comment by Langlaeufer** [comment]
thanks for repairing this!

An other point:
The calculated monthly and weekly goal is not logical.

Today, it is 22. November, 27 km to reach the yearly goal
As I understand you calculate:
2 Months left --> 27 km / 2 month  = 14 km / month
And then you tell me i have already 23 km this month of the 14 km done, but that is not correct, because the 14 km are based on the fact that i did 23 km already this month. 

In fact, at begin of november I had to run 50 km = 23 km (already done) + 27 km (left now)
So my november goal is 50km/2 = 25 km and I have at the moment 23/25 km .

**Comment by Holiverh** [comment]
Right, yes, when framed like that, the monthly and weekly goals probably shouldn't be moving targets as you say. It's something I wasn't sure on initially -- I should've asked for comments about it in the first PR really.

**Comment by thomaschampagne** [comment]
@Holiverh Thanks releasing it this week ! And no problems about testing ;) It's opensource project made on free time ! Stravistix is not a company. There is no employee ! You don't have any constraints ;) You probably did this work for you, for community and for fun. So no worries at all ! I saw efforts you made on code, comments, ... just perfect !

I also had to test a bit PRs i received :D 

Tom

**Comment by thomaschampagne** [comment]
Hey @Holiverh !

Got a mail from a user about your great feature :) Does the problem below talk to you? Normal? Let me know if you want that i dig & fix the problem. Thanks for all again ! Tom !

Mail content:

>It looks like there is a bug in that part of the code. It is showing incorrect number of miles ridden for the month along with incorrect number of miles ridden this week. 
>unnamed 2
>According to the training calendar I have ridden 1012 miles, not 430, total miles this week are 43.7 as shown above. 
>unnamed

**Pull request merged**
