### PR TITLE
add option to hide posts from activity feed

### PR DESCRIPTION
**Pull request by mckennajones**
For issue #472 

My first time contributing. Let me know if I left anything out.

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@mckennajones Thanks for the PR mate ;) Sorry the delay of handling... 

You work seems to do the job. Unfortunately feed auto-scrolling seems not working on my side when your option is activated.

Thanks !

Tom

**Comment by mckennajones** [comment]
Hey @thomaschampagne  I'll look into this sometime today.

**Comment by mckennajones** [comment]
@thomaschampagne to me it's not exactly clear what the autoscrolling setting is actually doing... Without without the autoscrolling setting turned on, when I reach the bottom of the page the new activities automatically load. Is there some functionality that I am missing? Thanks.

**Comment by thomaschampagne** [comment]
@mckennajones No you got it right :) I will try to figure out why it can't work on my side.

**Comment by thomaschampagne** [comment]
@mckennajones Just seen that strava put an auto scroll in their new UI.

Maybe problem come from autoscroll from stravistix. I will try by disabling/removing it when i have time.

The setting: https://github.com/thomaschampagne/stravistix/blob/develop/plugin/common/scripts/UserSettings.ts#L210

**Comment by mckennajones** [comment]
@thomaschampagne Ah I see, the setting was created before Strava had the autoscroll feature. I can make a quick PR remove that setting.

**Pull request merged**
