### PR TITLE
Enable Google Maps also in Analysis View

### PR DESCRIPTION
**Pull request by KamensekD**

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Hi @KamensekD,

Thanks for your pull request ! Thanks again for your involvement !

I tried to your enhancement yesterday. Unfortunately it seems not working onto my current develop branch :( 

I will try to solve the problem by myself unless you are able to find out the problem in seconds :)

Thanks again,

Cheers,

Tom

**Comment by KamensekD** [comment]
Hi Thomas! It should work if You start-off from analysis view or refresh page when coming to analysis mode from other pages ;)

**Comment by thomaschampagne** [comment]
Hi @KamensekD ,

I tried again i'm not able to get it working from overview to analysis. However it's work indeed if we hit directly analysis section.

I will probably delay the pull request from 2.1.0 milestone. To seal that thing and deliver it in next release.

Thanks again for your involvement !

Tom

**Comment by KamensekD** [comment]
Hello Thomas!

I guess it was easier to make it fully workable in my fork, because of a bit different aproach - I have "always present" Google maps button on left pane. In Your fork, "view in google maps" button is shown on overview page, but not on analysis page. Easiest solution for Your fork would be moving GM button.

I'm happy to give at least something back and thanx again for awesome work on StratistiX!
Keep it up!

Best Regards,
Dejan
sLOVEnia

**Comment by thomaschampagne** [comment]
Hi @KamensekD,

Thanks for reply. I placed button near maps to allow google map viewing on segment efforts too.

Current google maps stuff on stravistix master branch is doing 99% of work. 

I will delay "the final work" i have to put in if i'm merging this PR.

So i will place the PR in pending at the moment, and not deliver it in 2.1.0.

Thanks again !

Tom

**Pull request closed without merging**
