### PR TITLE
Median cadence and cadence std dev added

### PR DESCRIPTION
**Pull request by erikvankempen**
I've added median cadence and cadence standard deviation to the content summary grid (if user has opted to include cadence stats in the extended views). I (and a few of my friends) found this information useful during focused cadence training.

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Hi @erikvankempen ,

Thanks for your involment in the extension.

I'll take a look at this asap. Merging this seems to be ok.

Thanks!

**Comment by erikvankempen** [comment]
Cool! Thanks for the quick review and fix of my code. I'll keep you posted for future added features. Thanks for your work so far!

**Comment by thomaschampagne** [comment]
Thanks to you for stuff and time you put in ! 

I hope you will provide some new things for future.

Cheers,

Tom

**Comment by erikvankempen** [comment]
The standard deviation of cadence seems to be not working at the moment. I will take a look at this asap.

**Comment by thomaschampagne** [comment]
Yes, i've seen that it's always 0.

Thanks for your help ;)

Tom

**Pull request merged**
