### PR TITLE
Add monthly and weekly targets for strava premium annual goals

### PR DESCRIPTION
**Pull request by Holiverh**
This adds two new progress bars to the user's goals which track progress towards an annual goal but for for the current month and week. I think this satisfies #274 for the most part, except it doesn't do daily tracking. I'd be happy to add that as well if wanted.

goals

I'm not entire sure if I added the new `displayExtendedGoals` setting correctly. I had to do some manually jiggling to get it to work. It seemed to be confused because the setting didn't previously exist so it showed up as `undefined`? 😕

### CODE REVIEW

**Comment by tazmanska** [comment]
Awesome job!

**Comment by thomaschampagne** [comment]
OMG !! Nice work !!

I will test this at home !

Thanks !

**Comment by tariquesani** [comment]
Wow! So wanted this feature

**Comment by thomaschampagne** [comment]
@Holiverh Coming back to your PR to merge it this week and release :)

Do you confirm your feature works only for premium users?

Thanks again :)

**Comment by Holiverh** [comment]
Sadly, yes, this would only work for Strava Premium. However, it has only just occurred to me that this change will almost certainly break if the user uses imperial units instead of metric. I'll look to update it within the week.

**Comment by thomaschampagne** [comment]
@Holiverh No problem ;)

I was asking about this because a similar "targets" system has be introduced in stravistix:

image
(You can view this target  in year progression graph (my profile))

I have to avoid confusion between "targets" system for premium/free users. 

Maybe should we use always strava targets values for premium users and always stravistix targets values for free users.

Let me know what do you all think about.

Thanks for the clean and nice code of your PR :) It's well commented ;)

Thomas

**Comment by thomaschampagne** [comment]
@Holiverh Thanks for your work. Your PR has been released in 4.5.0 ;)

**Comment by thomaschampagne** [comment]
@Holiverh A user sent me this question few seconds ago:

>Hello Thomas,

>Where came the numbers from?
cycling: 
my settings: 3500 km / year,  77 km left
1749 km / month and 437 km / week

>running:
my settings: 600 km / year , 27 km left 
14 km / month and 3 km / week ?

>Best regards
Frank

>unnamed
>unnamed 2

Are his numbers correct? 

On my side i'm not sure to understand that he has to done "1749 km / month'" for November 2016 since he has already done "3433/3500km" for 2016. 

Thanks again for your work (and clean commented code).

Tom ;)

**Comment by Langlaeufer** [comment]
The problem comes from german number format. (point for thousand seperator) 
with english language settings it works perfect.

**Comment by Langlaeufer** [comment]
Now swimming is wrong.
image

**Pull request merged**
