### PR TITLE
Enhancement: Veloviewer OCM/OSM MapFlipper - with Icon Links and tooltips

### PR DESCRIPTION
**Pull request by KamensekD**
This one replaces my previous "Patch 2 - Veloviewer Map Flipper"

### CODE REVIEW

**Comment by KamensekD** [comment]
mapflipper with icons

**Comment by thomaschampagne** [comment]
I will check your work and see what i can merge after 0.6.0

Thanks for all !

**Comment by KamensekD** [comment]
Hi Thomas! I'm happy to help improve the plugin, hope You'll like some of my ideas.

RPE is Rated Perceived Exertion (look at http://my.clevelandclinic.org/services/heart/prevention/exercise/rpe-scale) - it is a scale 1-10 to somehow measure workout by it's intensity. It is pretty widely used; sometimes scale 1-20 is used for it.
By comparing info about RPE and a lot of my workouts I found out, it is very much correlated to TRIMP per hour.
http://completely-fit.com/blog/exercise/rpe-rate-of-perceived-exertion/
rpe-142x300
https://www.pinterest.com/pin/450219293973300940/
rpe

**Comment by KamensekD** [comment]
btw.: just hover mouse over TRIMP, TRIMP/hour and RPE gauge and You get tooltips explaining it shortly ;)

**Comment by thomaschampagne** [comment]
@KamensekD FYI i'm handling OSM support through your ticket  #66

**Comment by thomaschampagne** [comment]
I will not merge this pull request automatically. I will get stuff by hand.

Thanks !

**Pull request closed without merging**
