### PR TITLE
Enhancement #195

### PR DESCRIPTION
**Pull request by praveentiru**
Code to implement enhancement #195 

One can track annual targets for both distance and time by activity. Sample snap shots:
distance_trend
distance_last_30d
time

Please review and comment

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@praveentiru Woow !! Awesome !!!
Where do you store the target value?

**Comment by praveentiru** [comment]
@thomaschampagne Hey Tom, I re-used the target values that Strava allows premium users to set. As discussed, you can change this to allow stravistix users to set targets.

**Comment by thomaschampagne** [comment]
@praveentiru I integrated your work +mine for setup target (ride+run) for all account (free/premium) in **feature/195** branch.

Soon finishing feature to merge to develop and release in 3.7.0.

Thanks for the nice feature ! Again and Again :)

**Comment by praveentiru** [comment]
@thomaschampagne you are welcome.

**Comment by thomaschampagne** [comment]
@praveentiru Closing this PR since it's now in https://github.com/thomaschampagne/stravistix/tree/feature/195 (for free account setup adjustements)

Same https://github.com/thomaschampagne/stravistix/issues/195 has been linked to milestone https://github.com/thomaschampagne/stravistix/milestones/3.7.0

**Pull request closed without merging**
