### PR TITLE
Heart rate adjusted recent efforts graph

### PR DESCRIPTION
**Pull request by OndrejSpanel**
Add heart rate adjusted performance into the segment Recent efforts graph - pace is adjusted for running, power for riding. The intention is to show the approximate fitness history in the segment.

Performance is adjusted based on assumption pace / power is linear to HRR, see [Tracking Fitness With the "Heart Rate-Running Speed Index"](http://www.runnersworld.com/sweat-science/tracking-fitness-with-the-heart-rate-running-speed-index). The highest HR from efforts in the segment is used as a target HR to which all other efforts are readjusted.

Only efforts with HR data are included in the graph, no graph is created unless there are at least two efforts present with HR data.

Option is added for this, by default true.

Screenshot - running:

image

Screenshot - bike:

image

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Omg ! Woow !!! I just tested that ! Nice idea ! Nice work ! Tested on a favorite climb cycling segment. Pretty usefull.

I don't know if it's easy to see the hr/power value in the tooltip of strava? I will try to make this. Unless you convince me to not do it because you can do it in few seconds or it's useless ^^^.

Don't worry with "codacy" code checking ;) There lot of warning all over the project ;)

Moreover I'm currently moving all the project for 2 weeks to TypeScript (https://www.typescriptlang.org/ : OpenSource javascript compilator by microsoft also used in angular2). It's pretty powerfull !! No more javascript idiot error,... Typings like JAVA.. easiest dev into IDE (atom, webstorm,...), Inheritance, Interface, arrows function, .... Easy to use Compilation to es5, es2015, es6...

So after merging you PR, i will write i convert it by hand to TypeScript. Codady errors should say bye bye.

Thanks again for your work ! I given to good step to the plugin :) Opensource is cool :)

Thanks and Cheers!

Tom

**Comment by OndrejSpanel** [comment]
> you can do it in few seconds

I have already tried to add a SVG tooltip, but normal way did not work, and I did not spend much time on it. My guess is some Strava script is already handling the hover mouse events.

Note:  note - normally tooltips in SVG are added by using a `<title>` child element, not a `title` attribute as in HTML.

**Comment by thomaschampagne** [comment]
@OndrejSpanel I will handle your PR soon. I had to convert it to TypeScript first.

Don't worry i will merge this in few days ;)

Thanks again for your work !

Tom

**Comment by thomaschampagne** [comment]
Hi,

I'm not able to see HR y axis like previously on runnning segments? Is this normal? It's working with cycling (power axis displayed)

screenshot from 2016-10-11 11-22-11

Thanks again !

Tom

**Comment by OndrejSpanel** [comment]
Yes, this is normal, for running the y-axis is common with the normal values, the values displayed for running are "time".

**Comment by thomaschampagne** [comment]
@OndrejSpanel Your pull request is merged :smile: 

What i have done:

1. Converted your code to typescript (more efficiency than JS for sure !). It will be converted to JS on compile.
2. Put feature in hidden/beta at the moment: I let you add missing explanation you described to ensure user understand well the feature. (cycling > power ; running > HR)

Let me know if you encounter any problem with typescript. You shouldn't (just follow README.md)

Thanks again for this amazing work !!

Tom

**Pull request merged**
