### PR TITLE
fixbug: bikeOdo for some bike names

### PR DESCRIPTION
**Pull request by KamensekD**
If bike name contains UTF8 characters, bike odo display doesn't work - error in console:

>*Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.*

**Fixed** - see:
http://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Thanks for this.

However the bike odo cache system do not work anymore with this fix.

**Comment by thomaschampagne** [comment]
I will fint out why. But not this week :)

**Comment by KamensekD** [comment]
I guess fix in file **hook/extension/js/modifiers/ActivityBikeOdoModifier.js** needs to be done to make proper cache reads: https://github.com/thomaschampagne/StravaPlus/commit/b9d23731c226d7d894a9b2801736368522cfda40

**Comment by thomaschampagne** [comment]
I will not merge this pull request automatically. I will get stuff by hand.

Thanks !

**Pull request closed without merging**
