### PR TITLE
User can see best splits in their cycling activities

### PR DESCRIPTION
**Pull request by tazmanska**

### CODE REVIEW

**Comment by thomaschampagne** [comment]
YEAHHHHHH !!!! THANKS !!

I will do some testing of course. Opening some issues on your repo if needed.

Thanks Thanks Thanks !!

**Comment by thomaschampagne** [comment]
@tazmanska FYI This pull request has been fetched into 

View @ https://github.com/thomaschampagne/stravistix/tree/pull/125

I enhanced things in. I will add a "reset best split config" button too. You will be notified when **pull/125** branch (build from your PR) will be merged into my *git flow* **develop** branch.

Thanks for all !

Tom

**Comment by thomaschampagne** [comment]
Hi Tomasz,

I merged your feature into develop. I'm currently will releasing it.

Do you have twitter account for crediting you about this awesome work?

Have a nice day !

Thomas

**Comment by tazmanska** [comment]
@thomaschampagne Nope, I don't tweet :)

**Pull request closed without merging**
