### PR TITLE
Sliding graph : year / 30d

### PR DESCRIPTION
**Pull request by glandais**
distance-last-sliding-30d
distance-last-sliding-year

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@glandais Woow !!! Nice one !!! I will see this at home :)

Seems to be a killer feature ! Thanks for this work !

**Comment by thomaschampagne** [comment]
@glandais I retreived your pull request into the following branch of my repo: https://github.com/thomaschampagne/stravistix/tree/pull/190

I fixed an *"undefined $activityUrl"* error i got when testing your PR through the commit https://github.com/thomaschampagne/stravistix/commit/5c67a096b5c58174d3da3a67c6d676bd5f32ed35 on same "pull/190" branch of my repo.

I wasn't able to display your new feature on this branch into "My year progressions to current month/day"

Note: I only have 2 zwift virtual ride in 2016

Thanks for all again.

Thomas

(i could write this to you in french ;), but it's public, so english ;))

**Comment by glandais** [comment]
I'm struggling with git... I'll try again later :(

**Comment by thomaschampagne** [comment]
No problems ;) Tell me if you need any help with git.

**Pull request closed without merging**
